name: Lint and push

on:
  push:
    branches:
      - main

jobs:
  lint-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Check for lint changes
        id: git-status
        run: echo ::set-output name=changed::$(git status --porcelain app/page.tsx)

      - name: Commit linted changes
        if: steps.git-status.outputs.changed == "M app/page.tsx"
        run: |
          git config user.email "gcalcada7@ua.pt"
          git config user.name "gcalcadaMctw"
          git add .
          git commit -m "Linted Working #3"
          git fetch
          git push origin main